199
USGS-WiM/stnweb2 pull request #214
Opened 2021-06-15 16:06 UTC by Abigail770

- Added map filters to sidebar in filter.component.ts.  I used Event Emitters to pass values from the filter component to the map component.  **If you could take a look at my code in filter.component.ts, that would be great!  There may be a better way in Angular of handling interactions between the filter and map component than what I have set up.**
- Added map filters button for mobile screen sizes (max-width 875px).  The map filter accordions are hidden on mobile.  When the map filters button is clicked, the map and filter results are hidden and the map filters are shown.  On submit or clear, the filters are hidden and map and results are shown.
- Desktop vs. mobile layout updates when the window is resized.
- I placed the map filters in an accordion.  When one dropdown filter is opened, any others that are open are collapsed.
- I added a media query to set the min-width of the map container to be less than a mobile screen width, to avoid overflowing the html container width (min-width is still at 550px on desktop sizes).  

**I noticed a couple other issues on mobile that I didn't address:**
-Some of the header elements are overflowing the width of the html container on mobile
-legend and Minimize Map button overlap on mobile
I can create a new issue for these (or two separate issues), whichever you would prefer.

2021-06-16 18:21 UTC, lprivette commented
Oops sorry I forgot to review this yesterday! Is it ready to be reviewed/merged @Abigail770 ?

2021-06-16 19:07 UTC, Abigail770 commented
Now it's ready!  If you could look over the changes to the code when you get a chance too, that would be great (filter.component.ts and html, map.component.ts and html).  Everything is functioning as it should, but I just want to make sure I'm following best coding practices, etc. since I'm new to Angular.

2021-06-21 20:30 UTC, lprivette commented on src/app/map/map.component.ts
> +    // public removable = true;
If this isn't being used lets go ahead an remove it.

If you'd like to leave it in for some future reason just add an explanation comment.

2021-06-21 22:18 UTC, lprivette requested changes
Looks good! I actually haven't used EventEmitters before, but they're part of the angular core so that's good enough for me. You could have used an obsverable/service but I don't think one choice is better than the other for this.

Once you address that one commented out variable, I'll go ahead and merge this into dev.

2021-06-28 16:25 UTC, lprivette approved these changes

2021-06-28 16:29 UTC, merged